name: Cypress Tests

on:
  push:
    branches:
      - sprint4
  pull_request:
    branches:
      - sprint4

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
  
        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '14'
  
        - name: Install Cypress
          run: npm install cypress --save-dev  # Instalação local do Cypress
  
        - name: Run Cypress Tests
          run: npx cypress run  # Comando para executar os testes Cypress
